[operators]
[operators.sim_atmosphere_coarse]
    class = "toast.ops.sim_tod_atm.SimAtmosphere"
    API = 0 # Internal interface version for this operator
    add_loading = false # Add elevation-dependent loading.
    cache_dir = "atm_cache_coarse" # Directory to use for loading / saving atmosphere realizations
    cache_only = false # If True, only cache the atmosphere, do not observe it.
    component = 123456 # The component index to use for this atmosphere simulation
    debug_plots = false # If True, make plots of the debug snapshots
    debug_snapshots = false # If True, dump snapshots of the atmosphere slabs to pickle files
    debug_spectrum = false # If True, dump out Kolmogorov debug files
    debug_tod = false # If True, dump TOD to pickle files
    det_data = "signal" # Observation detdata key for accumulating atmosphere timestreams
    det_flag_mask = 0 # Bit mask value for optional detector flagging
    det_flags = "flags" # Observation detdata key for flags to use
    detector_pointing = "None" # Operator that translates boresight Az/El pointing into detector frame
    detector_weights = "None" # Operator that translates boresight Az/El pointing into detector weights
    enabled = true # If True, this class instance is marked as enabled
    fade_time = "6.00000000000000e+01 s" # Fade in/out time to avoid a step at wind break.
    field_of_view = "None" # Override the focalplane field of view
    freq = "None" # Observing frequency
    gain = 0.0006 # Scaling applied to the simulated TOD
    lmax_center = "1.00000000000000e+04 m" # Kolmogorov turbulence injection scale center
    lmax_sigma = "1.00000000000000e+03 m" # Kolmogorov turbulence injection scale sigma
    lmin_center = "3.00000000000000e+02 m" # Kolmogorov turbulence dissipation scale center
    lmin_sigma = "3.00000000000000e+01 m" # Kolmogorov turbulence dissipation scale sigma
    n_bandpass_freqs = 100 # The number of sampling frequencies used when convolving the bandpass with atmosphere absorption and loading
    name = "sim_atmosphere_coarse" # The 'name' of this class instance
    nelem_sim_max = 30000 # Controls the size of the simulation slices
    overwrite_cache = false # If True, redo and overwrite any cached atmospheric realizations.
    polarization_fraction = 0.0 # Polarization fraction (only Q polarization).
    realization = 1000000 # If simulating multiple realizations, the realization index
    sample_rate = "None" # Rate at which to sample atmospheric TOD before interpolation.  Default is no interpolation.
    shared_flag_mask = 0 # Bit mask value for optional shared flagging
    shared_flags = "flags" # Observation shared key for telescope flags to use
    times = "times" # Observation shared key for timestamps
    turnaround_interval = "turnaround" # Interval name for turnarounds
    view = "None" # Use this view of the data in all observations
    wind_dist = "1.00000000000000e+04 m" # Maximum wind drift before discarding the volume and creating a new one
    xstep = "5.00000000000000e+01 m" # Size of volume elements in X direction
    ystep = "5.00000000000000e+01 m" # Size of volume elements in Y direction
    z0_center = "2.00000000000000e+03 m" # Central value of the water vapor distribution
    z0_sigma = "0.00000000000000e+00 m" # Sigma of the water vapor distribution
    zatm = "4.00000000000000e+04 m" # Atmosphere extent for temperature profile
    zmax = "2.00000000000000e+03 m" # Atmosphere extent for water vapor integration
    zstep = "5.00000000000000e+01 m" # Size of volume elements in Z direction

[operators.sim_atmosphere]
    class = "toast.ops.sim_tod_atm.SimAtmosphere"
    API = 0 # Internal interface version for this operator
    add_loading = true # Add elevation-dependent loading.
    cache_dir = "atm_cache" # Directory to use for loading / saving atmosphere realizations
    cache_only = false # If True, only cache the atmosphere, do not observe it.
    component = 123456 # The component index to use for this atmosphere simulation
    debug_plots = false # If True, make plots of the debug snapshots
    debug_snapshots = false # If True, dump snapshots of the atmosphere slabs to pickle files
    debug_spectrum = false # If True, dump out Kolmogorov debug files
    debug_tod = false # If True, dump TOD to pickle files
    det_data = "signal" # Observation detdata key for accumulating atmosphere timestreams
    det_flag_mask = 0 # Bit mask value for optional detector flagging
    det_flags = "flags" # Observation detdata key for flags to use
    detector_pointing = "None" # Operator that translates boresight Az/El pointing into detector frame
    detector_weights = "None" # Operator that translates boresight Az/El pointing into detector weights
    enabled = true # If True, this class instance is marked as enabled
    fade_time = "6.00000000000000e+01 s" # Fade in/out time to avoid a step at wind break.
    field_of_view = "None" # Override the focalplane field of view
    freq = "None" # Observing frequency
    gain = 6e-05 # Scaling applied to the simulated TOD
    lmax_center = "1.00000000000000e+00 m" # Kolmogorov turbulence injection scale center
    lmax_sigma = "1.00000000000000e-01 m" # Kolmogorov turbulence injection scale sigma
    lmin_center = "1.00000000000000e-03 m" # Kolmogorov turbulence dissipation scale center
    lmin_sigma = "1.00000000000000e-04 m" # Kolmogorov turbulence dissipation scale sigma
    n_bandpass_freqs = 100 # The number of sampling frequencies used when convolving the bandpass with atmosphere absorption and loading
    name = "sim_atmosphere" # The 'name' of this class instance
    nelem_sim_max = 10000 # Controls the size of the simulation slices
    overwrite_cache = false # If True, redo and overwrite any cached atmospheric realizations.
    polarization_fraction = 0.0 # Polarization fraction (only Q polarization).
    realization = 0 # If simulating multiple realizations, the realization index
    sample_rate = "None" # Rate at which to sample atmospheric TOD before interpolation.  Default is no interpolation.
    shared_flag_mask = 0 # Bit mask value for optional shared flagging
    shared_flags = "flags" # Observation shared key for telescope flags to use
    times = "times" # Observation shared key for timestamps
    turnaround_interval = "turnaround" # Interval name for turnarounds
    view = "None" # Use this view of the data in all observations
    wind_dist = "3.00000000000000e+03 m" # Maximum wind drift before discarding the volume and creating a new one
    xstep = "5.00000000000000e+00 m" # Size of volume elements in X direction
    ystep = "5.00000000000000e+00 m" # Size of volume elements in Y direction
    z0_center = "2.00000000000000e+03 m" # Central value of the water vapor distribution
    z0_sigma = "0.00000000000000e+00 m" # Sigma of the water vapor distribution
    zatm = "4.00000000000000e+04 m" # Atmosphere extent for temperature profile
    zmax = "2.00000000000000e+02 m" # Atmosphere extent for water vapor integration
    zstep = "5.00000000000000e+00 m" # Size of volume elements in Z direction